spring:
  application:
    name: atm-messages-producer
  pulsar:
    client:
      service-url: pulsar://localhost:6650
    producer:
      send-timeout-ms: 10000
    consumer:
      dead-letter-policy-max-redeliver-count: 3
    admin:
      service-url: http://localhost:8080

pulsar:
  topic:
    name: atm-raw-data
server:
  port: 8081