spring:
  application:
    name: atm-registry-service
    # Database Connection Properties
  datasource:
    url: jdbc:postgresql://localhost:5432/atm_registry_db
    username: postgres
    password: foo
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # Schema Generation (Choose ONE strategy)
    hibernate:
      # Option 1: Automatic (Good for quick development/testing, NOT recommended for production)
      ddl-auto: update
      # Option 2: Using Migration Tools (Recommended for Dev/Prod) - Set to 'validate' or 'none'
      # ddl-auto: validate
    # Show SQL statements in logs (Optional, useful for debugging)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Logging Levels (Optional)
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8085