global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Eureka Server monitoring (static port)
  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8761']

  # API Gateway monitoring (static port)
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']

  # Dynamic services discovered through Eureka
  - job_name: 'eureka-services'
    metrics_path: '/actuator/prometheus'
    eureka_sd_configs:
      - server: 'http://host.docker.internal:8761/eureka'
        refresh_interval: 15s
    relabel_configs:
      # Set application name
      - source_labels: ['__meta_eureka_app_name']
        target_label: 'application'

      # Extract port from Eureka metadata
      - source_labels: ['__meta_eureka_app_instance_port']
        target_label: 'eureka_port'

      # THIS IS THE CRITICAL FIX - hardcode host.docker.internal with the port
      - source_labels: ['__meta_eureka_app_instance_port']
        target_label: '__address__'
        regex: '(.+)'
        replacement: 'host.docker.internal:${1}'

      # Add instance label for display purposes
      - source_labels: ['__meta_eureka_app_instance_hostName', '__meta_eureka_app_name', '__meta_eureka_app_instance_port']
        separator: ':'
        target_label: 'instance'