spring:
  application:
    name: jbpm-incident-service
  datasource:
    url: jdbc:postgresql://localhost:5432/atm-incident-db
    username: postgres
    password: foo
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # Schema Generation (Choose ONE strategy)
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  pulsar:
    client:
      service-url: pulsar://localhost:6650
    producer:
      send-timeout-ms: 10000
    consumer:
      dead-letter-policy-max-redeliver-count: 3
    admin:
      service-url: http://localhost:8080
pulsar:
  consumer:
    incident-topic: internal-atm-incident-events

    subscription-name: atm-state-service-subscription

kie:
    server:
        url: http://localhost:8080/kie-server/services/rest/server
        username: wbadmin
        password: wbadmin
        timeout: 30000
    container:
      id: Incident-Management_1.0.0-SNAPSHOT
    process:
      id: IncidentManagement.IncidentManagementProcess
server:
  port: 8081