spring:
  application:
    name: atm-api-gateway

server:
  port: 8761

# Expose Prometheus metrics endpoint
management:
  tracing:
    sampling:
      probability: 1.0
    baggage:
      remote-fields: "*"
      correlation:
        fields: "*"
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
    tracing:
      endpoint: http://localhost:4318/v1/traces
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}



eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
