spring:
  application:
    name: atm-api-gateway

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: prometheus


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
